### Endpoit para Criar Uuário

POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Maya",
    "email": "email@example2.com",
    "password": "654321"
}

### Endpoint para criar post
POST http://localhost:3003/post
Content-Type: application/json

{
    "photo": "Foto Minha",
    "description": "Foto Minha Sorrindo!",
    "type": "normal",
    "author_id": "167552131065"
}

### Buscar post por id

GET http://localhost:3003/posts/:id
Content-Type: application/json

{
    "id": "1675523803176"
}